language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

script:
  - npm run codecheck

notifications:
  email:
    recipients:
      - 1170212530@qq.com
    on_success: never
    on_failure: always
